name: docs
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-python-version: '3.10'

      - name: Install tt-support-tools
        run: pip install git+https://github.com/tinytapeout/tt-support-tools.git

      - name: build docs
        run: tt_tool.py --create-user-docs

      - name: deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
